# Generated by Django 5.1.6 on 2025-03-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='appointment_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن بخش رزرو نوبت'),
        ),
    ]
