# Generated by Django 5.1.6 on 2025-03-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_sitesetting_appointment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='appointment_url',
            field=models.CharField(default=1, max_length=200, verbose_name='لینک نوبت دهی'),
            preserve_default=False,
        ),
    ]
