# Generated by Django 5.1.6 on 2025-03-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url', models.URLField(blank=True, max_length=400, null=True, verbose_name='لینک')),
                ('image', models.ImageField(upload_to='images/banners', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('position', models.CharField(choices=[('home-page', 'صفحه اصلی'), ('common-pages', 'صفحات عمومی')], max_length=200, verbose_name='جایگاه')),
            ],
            options={
                'verbose_name': 'بنر سایت',
                'verbose_name_plural': 'بنرهای سایت',
            },
        ),
    ]
