# Generated by Django 5.1.6 on 2025-03-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_sitebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='images/site_images', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('position', models.CharField(choices=[('in banner', 'تصویر داخل بنر'), ('about dr', 'تصویر قسمت درباره ی پزشک')], max_length=200, verbose_name='جایگاه')),
            ],
            options={
                'verbose_name': 'تصویر سایت',
                'verbose_name_plural': 'تصاویر سایت',
            },
        ),
    ]
