# Generated by Django 5.1.6 on 2025-03-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_siteimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('whatsapp_url', models.URLField(max_length=300, verbose_name='نشانی واتس اپ')),
                ('instagram_url', models.URLField(max_length=300, verbose_name='نشانی اینستاگرام')),
                ('is_main_urls', models.BooleanField(verbose_name='آیا لینک های اصلی است؟')),
            ],
            options={
                'verbose_name': 'لینک شبکه های اجتماعی',
                'verbose_name_plural': 'لینک های شبکه های اجتماعی',
            },
        ),
    ]
