# Generated by Django 5.1.6 on 2025-03-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqmodel',
            options={'verbose_name': 'پرسش و پاسخ', 'verbose_name_plural': 'پرسش و پاسخ ها'},
        ),
    ]
