# Generated by Django 5.1.6 on 2025-03-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_module', '0002_alter_faqmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqmodel',
            name='question',
            field=models.TextField(verbose_name='سوال'),
        ),
    ]
