# Generated by Django 5.1.6 on 2025-03-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_module', '0003_alter_faqmodel_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=200, verbose_name='ایمیل')),
                ('mobile', models.CharField(max_length=200, verbose_name='موبایل')),
                ('subject', models.CharField(db_index=True, max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='متن')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('response', models.TextField(verbose_name='پاسخ')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='آیا توسط ادمین دیده شده است؟')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'ارتباط با ما',
            },
        ),
    ]
