# Generated by Django 5.1.6 on 2025-03-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcategory',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
