# Generated by Django 5.1.6 on 2025-03-04 13:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0002_rename_is_delete_blogcategory_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='متن'),
        ),
    ]
