# Generated by Django 5.1.6 on 2025-03-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0003_alter_blog_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='quotes',
        ),
    ]
