# Generated by Django 5.1.6 on 2025-03-04 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0004_remove_blog_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=200, verbose_name='تگ')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_tags', to='blog_module.blog', verbose_name='مقاله ی مربوطه')),
            ],
            options={
                'verbose_name': 'تگ بلاگ',
                'verbose_name_plural': 'تگ های بلاگ ها',
            },
        ),
    ]
