# Generated by Django 5.1.6 on 2025-03-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0005_blogtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='en_title',
            field=models.CharField(default=1, max_length=100, verbose_name='عنوان به انگلیسی'),
            preserve_default=False,
        ),
    ]
