# Generated by Django 5.1.6 on 2025-03-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0006_blog_en_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_services',
            field=models.BooleanField(default=False, verbose_name='آیا این مقاله جزء دسته ی خدمات است؟'),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_women_issues',
            field=models.BooleanField(default=False, verbose_name='آیا این مقاله جزء دسته ی بیماری ها و مسائل زنان است؟'),
        ),
    ]
