# Generated by Django 5.1.6 on 2025-03-04 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0007_blog_is_services_blog_is_women_issues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_index=True, verbose_name='متن کامنت')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تایید شده / نشده')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_module.blog', verbose_name='مقاله')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_module.blogcomments', verbose_name='والد کامنت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر مقاله',
                'verbose_name_plural': 'نظرات مقاله ها',
            },
        ),
    ]
