# Generated by Django 5.1.6 on 2025-03-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0008_blogcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomments',
            name='subject',
            field=models.CharField(db_index=True, default=1, max_length=100, verbose_name='موضوع کامنت'),
            preserve_default=False,
        ),
    ]
