# Generated by Django 5.1.6 on 2025-03-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0009_blogcomments_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رنگ'),
        ),
    ]
