# Generated by Django 5.1.6 on 2025-03-08 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0010_blogcategory_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog_module.blogcomments', verbose_name='والد کامنت'),
        ),
    ]
