# Generated by Django 5.1.6 on 2025-03-09 17:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0013_alter_blogcomments_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن'),
        ),
    ]
