# Generated by Django 5.1.6 on 2025-03-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0014_alter_blog_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='url_title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='عنوان(انگلیسی)'),
        ),
    ]
