# Generated by Django 5.1.6 on 2025-03-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0015_alter_blogcategory_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
    ]
