# Generated by Django 5.1.6 on 2025-03-04 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0007_blog_is_services_blog_is_women_issues'),
        ('home_module', '0002_alter_services_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
        migrations.RemoveField(
            model_name='services',
            name='image',
        ),
        migrations.RemoveField(
            model_name='services',
            name='title',
        ),
        migrations.AddField(
            model_name='services',
            name='related_service',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog_module.blog', verbose_name='مقاله ی مربوطه'),
            preserve_default=False,
        ),
    ]
