# Generated by Django 5.1.6 on 2025-03-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_remove_services_description_remove_services_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='related_service',
            new_name='related_blog',
        ),
    ]
