# Generated by Django 5.1.6 on 2025-03-03 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_module', '0002_alter_services_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دکتر')),
                ('image', models.ImageField(upload_to='images/doctor/', verbose_name='تصویر')),
                ('short_bio', models.TextField(verbose_name='بیوگرافی کوتاه')),
                ('biography', models.TextField(verbose_name='بیوگرافی')),
                ('is_main_dr', models.BooleanField(default=False, verbose_name='دکتر اصلی')),
                ('services_titles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_module.services', verbose_name='خدمات')),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشکان',
            },
        ),
    ]
