# Generated by Django 5.1.6 on 2025-03-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0001_initial'),
        ('home_module', '0002_alter_services_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrModel',
            new_name='Doctor',
        ),
    ]
