# Generated by Django 5.1.6 on 2025-03-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0002_rename_drmodel_doctor'),
        ('home_module', '0002_alter_services_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='services_titles',
        ),
        migrations.AddField(
            model_name='doctor',
            name='services_titles',
            field=models.ManyToManyField(to='home_module.services', verbose_name='خدمات'),
        ),
    ]
