# Generated by Django 5.1.6 on 2025-03-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0003_remove_doctor_services_titles_doctor_services_titles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='services_titles',
            new_name='services',
        ),
    ]
