# Generated by Django 5.1.6 on 2025-03-03 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0004_rename_services_titles_doctor_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'زمان',
                'verbose_name_plural': 'زمان ها',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100, verbose_name='روز')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('time_of_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_module.timeofday', verbose_name='وقت')),
            ],
            options={
                'verbose_name': 'زمان کاری',
                'verbose_name_plural': 'زمان های کاری',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_hour',
            field=models.ManyToManyField(to='about_module.workinghours', verbose_name='ساعات کاری'),
        ),
    ]
