# Generated by Django 5.1.6 on 2025-03-03 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0005_timeofday_workinghours_doctor_working_hour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'موضوع کامنت',
                'verbose_name_plural': 'موضوعات کامنت ها',
            },
        ),
        migrations.CreateModel(
            name='CommentsAboutDr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_index=True, verbose_name='متن کامنت')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='about_module.commentsaboutdr', verbose_name='والد کامنت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_module.commentsubjects', verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'نظر درباره پزشک',
                'verbose_name_plural': 'نظرات درباره پزشک',
            },
        ),
    ]
