# Generated by Django 5.1.6 on 2025-03-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0006_commentsubjects_commentsaboutdr'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsaboutdr',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='تایید شده / نشده'),
        ),
    ]
