# Generated by Django 5.1.6 on 2025-03-03 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0007_commentsaboutdr_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsaboutdr',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='about_module.commentsubjects', verbose_name='موضوع'),
        ),
    ]
