# Generated by Django 5.1.6 on 2025-03-04 14:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0008_alter_commentsaboutdr_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='biography',
            field=ckeditor.fields.RichTextField(verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='short_bio',
            field=ckeditor.fields.RichTextField(verbose_name='بیوگرافی کوتاه'),
        ),
    ]
