# Generated by Django 5.1.6 on 2025-03-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0009_alter_doctor_biography_alter_doctor_short_bio'),
        ('home_module', '0004_rename_related_service_services_related_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='home_module.services', verbose_name='خدمات'),
        ),
    ]
