# Generated by Django 5.1.6 on 2025-03-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0010_alter_doctor_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsaboutdr',
            name='is_show_in_home_page',
            field=models.BooleanField(default=False, verbose_name='آیا این دیدگاه در صفحه ی اصلی نمایش داده شود؟'),
        ),
    ]
