# Generated by Django 5.1.6 on 2025-03-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0011_commentsaboutdr_is_show_in_home_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractedHospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام بیمارستان')),
            ],
            options={
                'verbose_name': 'بیمارستان',
                'verbose_name_plural': 'بیمارستان ها',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='contracted_hospitals',
            field=models.ManyToManyField(blank=True, null=True, to='about_module.contractedhospitals', verbose_name='بیمارستان های طرف قرارداد'),
        ),
    ]
