# Generated by Django 5.1.6 on 2025-03-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0012_contractedhospitals_doctor_contracted_hospitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractedhospitals',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیر فعال'),
        ),
    ]
