# Generated by Django 5.1.6 on 2025-03-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0013_contractedhospitals_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractedhospitals',
            name='name',
            field=models.CharField(max_length=300, verbose_name='نام بیمارستان'),
        ),
    ]
