# Generated by Django 5.1.6 on 2025-03-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0014_alter_contractedhospitals_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام دکتر'),
        ),
    ]
