# Generated by Django 5.1.6 on 2025-03-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0016_rename_name_contractedhospitals_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='time_of_day',
            field=models.CharField(max_length=100, verbose_name='روز'),
        ),
        migrations.DeleteModel(
            name='TimeOfDay',
        ),
    ]
