# Generated by Django 5.1.6 on 2025-03-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0017_alter_workinghours_time_of_day_delete_timeofday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='time_of_day',
            field=models.CharField(max_length=100, verbose_name='موقع از روز(صبح/عصر)'),
        ),
    ]
