# Generated by Django 5.1.6 on 2025-04-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0018_alter_workinghours_time_of_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dr_panel_url',
            field=models.URLField(default=1, max_length=300, verbose_name='لینک پنل نوبت دهی دکتر'),
            preserve_default=False,
        ),
    ]
