# Generated by Django 5.1.6 on 2025-03-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_alter_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='کد فعالسازی کاربر'),
        ),
    ]
